/** Etichette leggibili e metadati sicuri per gli eventi dell'audit log. */
const ACTION_LABELS: Record<string, string> = {
  retention_cleanup: "Pulizia per conservazione dati",
  regenerate_ai_summary: "Rigenerazione riepilogo AI",
  complete_erasure_request: "Completamento cancellazione GDPR",
  review_media: "Revisione media",
  reprocess_media: "Rielaborazione media",
  create_source: "Creazione fonte",
  duplicate_source: "Duplicazione fonte",
  update_source: "Modifica fonte",
  delete_source: "Eliminazione fonte",
  pause_source: "Sospensione fonte",
  disable_source: "Disabilitazione fonte",
  enable_source: "Abilitazione fonte",
  update_source_schedule: "Modifica pianificazione fonte",
  regenerate_backup_codes: "Rigenerazione codici di recupero",
  logout: "Uscita",
  enable_2fa: "Attivazione 2FA",
  change_password: "Cambio password",
  create_export: "Creazione esportazione",
  retry_export: "Nuovo tentativo esportazione",
  download_export: "Download esportazione",
  update_ai_settings: "Modifica impostazioni AI",
  update_ai_provider: "Modifica provider AI",
  test_ai_provider: "Test provider AI",
  remove_watermark: "Rimozione filigrana",
  create_proxy_pool: "Creazione pool proxy",
  update_proxy_pool: "Modifica pool proxy",
  delete_proxy_pool: "Eliminazione pool proxy",
  create_proxy: "Creazione proxy",
  update_proxy: "Modifica proxy",
  delete_proxy: "Eliminazione proxy",
  test_proxy: "Test proxy",
  update_user_role: "Modifica ruolo utente",
  suspend_user: "Sospensione utente",
  activate_user: "Riattivazione utente",
  reset_2fa: "Reimpostazione 2FA",
  create_erasure_request: "Creazione richiesta di cancellazione",
  confirm_erasure_request: "Conferma richiesta di cancellazione",
  update_classifier_settings: "Modifica impostazioni classificatore",
  bulk_reprocess_media: "Rielaborazione massiva media",
  update_source_priority: "Modifica priorità fonte",
  view_clear_phone: "Visualizzazione telefono in chiaro",
};

export function auditActionLabel(action: string): string {
  return ACTION_LABELS[action] ?? action;
}
